# Generated by Django 5.0.3 on 2024-04-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('normal', 'normal'), ('medical_stuff', 'medical_stuff'), ('doctor', 'doctor')], default='normal', max_length=255)),
                ('first_name', models.CharField(default='None', max_length=255)),
                ('last_name', models.CharField(default='None', max_length=255)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(default='None', max_length=255)),
                ('gender', models.CharField(default='None', max_length=255)),
                ('medical_note', models.CharField(default='None', max_length=2000)),
                ('secret_key', models.CharField(default='expectropatronum', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('user_secret_share1', models.CharField(max_length=100)),
                ('user_secret_share2', models.CharField(max_length=100)),
                ('user_secret_share3', models.CharField(max_length=100)),
                ('doctor_secret_share1', models.CharField(max_length=100)),
                ('doctor_secret_share2', models.CharField(max_length=100)),
                ('doctor_secret_share3', models.CharField(max_length=100)),
                ('user_reconstructed_key', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('doctor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
