# Generated by Django 3.2.23 on 2024-04-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehandle',
            name='doctor_secret_share3',
        ),
        migrations.RemoveField(
            model_name='filehandle',
            name='user_secret_share2',
        ),
        migrations.RemoveField(
            model_name='filehandle',
            name='user_secret_share3',
        ),
    ]
