# Generated by Django 3.2.23 on 2024-04-30 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_prescription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_secret_share1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_secret_share2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_reconstructed_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_secret_share1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
