# Generated by Django 3.2.23 on 2024-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240430_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_secret_share1',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_secret_share2',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='file',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user_reconstructed_key',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user_secret_share1',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, upload_to='prescriptions/'),
        ),
    ]
