# Generated by Django 3.2.23 on 2024-05-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20240430_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehandle',
            name='doctor_secret_share1',
        ),
        migrations.RemoveField(
            model_name='filehandle',
            name='doctor_secret_share2',
        ),
        migrations.RemoveField(
            model_name='filehandle',
            name='user_reconstructed_key',
        ),
        migrations.RemoveField(
            model_name='filehandle',
            name='user_secret_share1',
        ),
    ]
