# Generated by Django 3.2.23 on 2024-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20240512_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandle',
            name='user_reconstructed_key',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
