# Generated by Django 3.2.23 on 2024-05-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_filehandle_user_reconstructed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandle',
            name='encrypted_content',
            field=models.BinaryField(default=b''),
        ),
    ]
