# Generated by Django 3.2.23 on 2024-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_filehandle_encrypted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandle',
            name='content_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
