# Generated by Django 3.2.23 on 2024-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_filehandle_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
