# Generated by Django 3.2.23 on 2024-07-16 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_time',
            field=models.DateTimeField(blank=True, db_column='approval_time', null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(db_column='approved', default=False),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='file',
            field=models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='base.filehandle'),
        ),
    ]
