# Generated by Django 3.2.23 on 2024-07-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20240716_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
