# Generated by Django 3.2.23 on 2024-07-19 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_approval_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('normal', 'normal'), ('medical_staff', 'medical_staff'), ('doctor', 'doctor')], default='normal', max_length=255),
        ),
    ]
