# Generated by Django 3.2.23 on 2024-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20240719_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='approved_doctor',
        ),
    ]
