# Generated by Django 3.2.23 on 2024-07-19 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_remove_account_approved_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_doctors',
            field=models.ManyToManyField(blank=True, related_name='approved_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
