# Generated by Django 3.2.23 on 2024-07-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_account_approved_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='requester_type',
            field=models.CharField(default='doctor', max_length=10),
        ),
    ]
