# Generated by Django 3.2.23 on 2024-07-25 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_approval_requester_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='requester',
            field=models.ForeignKey(db_column='requester_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='auth.user'),
            preserve_default=False,
        ),
    ]
